name: WebDAV Sync

on:
  schedule:
    - cron: '0 0 * * *'  # 每天00:00执行
  workflow_dispatch:      # 允许手动触发

jobs:
  sync_webdav:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 检出 GitHub 仓库代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. 安装 rclone
    - name: Install rclone
      run: |
        sudo apt-get update
        sudo apt-get install -y rclone

    # 3. 使用 rclone obscure 加密 WebDAV 密码并配置 rclone
    - name: Configure rclone
      run: |
        mkdir -p ~/.config/rclone
        # 生成rclone配置文件并将密码模糊化
        echo "[webdav]" > ~/.config/rclone/rclone.conf
        echo "type = webdav" >> ~/.config/rclone/rclone.conf
        echo "url = ${{ secrets.WEBDAV_URL }}" >> ~/.config/rclone/rclone.conf
        echo "vendor = other" >> ~/.config/rclone/rclone.conf
        echo "user = ${{ secrets.WEBDAV_USER }}" >> ~/.config/rclone/rclone.conf
        echo "pass = $(rclone obscure ${{ secrets.WEBDAV_PASSWORD }})" >> ~/.config/rclone/rclone.conf

    # 4. 使用 rclone 同步 WebDAV 文件到本地工作目录
    - name: Sync WebDAV content to local
      run: |
        rclone sync webdav:/ ${{ github.workspace }}/ --verbose

    # 5. 提交更改并推送到 GitHub
    - name: Commit changes
      run: |
        cd ${{ github.workspace }}
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Sync WebDAV content"
        git push origin main
